### ISSUE TITLE
Wireshark Dissector issue

### ISSUE THREAD

**Issue by wbw60** [famez/J1939-Framework#4] opened 2019-08-13 17:30 UTC
Has anyone had luck getting the Wireshark dissector to work? I am able to build it, but I noticed that it appears to conflict with the existing standard Wireshark J1939 dissector which takes precedence when you analyze a packet.  Thanks in advance for any help or pointers to information you can give me on this.

**Comment by famez** [comment] 2019-08-20 16:53
Can you check whether the plugin is properly loaded?

In Wireshark, go to Help -> About Wireshark -> Plugins.

**Comment by wbw60** [comment] 2019-08-20 20:20
Here's the Plugins list:  
![image](https://user-images.githubusercontent.com/47369051/63381202-354f9800-c366-11e9-851a-557993437894.png)

Error messages when I start wireshark up are: 
libEGL warning: DRI2: failed to authenticate
16:17:30.107     Main Warn QIODevice::read (QFile, "/usr/local/share/wireshark/COPYING"): device not open

**Comment by wbw60** [comment] 2019-08-20 20:26
This is on Raspian GNU/Linux 9 (stretch).  All 30 tests pass when I run execTests (I did  make a change to the path to the "test_not_found.json" path in database_test.cpp as I run execTests from the Tests dir).

**Comment by famez** [comment] 2019-08-20 21:24
Normally, it should work by right clicking over one can frame in the .pcap file, then choosing Decode as... and then select J1939 as protocol.

I don´t know if you followed these steps.

**Comment by wbw60** [comment] 2019-08-21 12:12
So here's some info from my compiled version:
![image](https://user-images.githubusercontent.com/47369051/63429544-5789fa00-c3e8-11e9-828a-ec1e79113dc6.png)
![image](https://user-images.githubusercontent.com/47369051/63429560-6375bc00-c3e8-11e9-9762-9f3269ee17ab.png)
![image](https://user-images.githubusercontent.com/47369051/63430004-8a80bd80-c3e9-11e9-926f-8bdfd52d3ae7.png)
Looking at the same file (the output of running gear_level.sh) on standard Wireshark on Windows after setting J1939 as the protocol looks like this:

![image](https://user-images.githubusercontent.com/47369051/63430503-b9e3fa00-c3ea-11e9-92a4-79971793fa1f.png)

Now what I thought I would see on the compiled version was what is in the main README file for the project:

![image](https://user-images.githubusercontent.com/47369051/63430662-1fd08180-c3eb-11e9-80e1-757d18def04c.png)

Any ideas on what I'm doing wrong that I don't see the message broken up into the SPN  components like on your screenshot? Thanks in advance for any info or pointers to info that you think would help!

**Comment by wbw60** [comment] 2019-08-21 12:14
Oops. Didn't mean to close the issue. :-(

**Comment by famez** [comment] 2019-08-21 21:42
Try opening the following pcap file. It contains a Vehicle Identification Number frame. If you are able to see it, the problem is that the database (frames.json) is not correctly loaded.


[vi.zip](https://github.com/famez/J1939-Framework/files/3527407/vi.zip)

**Comment by wbw60** [comment] 2019-08-22 16:05
FWIW, I noticed 3 errors in the packet-1939.cpp files that I had fixed in a previous build (I rebuilt everything and had managed to lose my previous changes). The line numbers are off due to including iostream for debug print statements:
++++++++++++++++++
402c401
< 		if(!pinfo->fd->visited) {		//Only treat the frames if it is the first time we see them!!!
---
> 		if(!pinfo->fd->flags.visited) {		//Only treat the frames if it is the first time we see them!!!
528,529c527,528
< 					spnNum->getByteSize(), spnNum->getFormattedValue(), "%s: %.10g %s",
< 					spn->getName().c_str(), spnNum->getFormattedValue(), spnNum->getUnits().c_str());
---
> 					spnNum->getByteSize(), spnNum->getFormatedValue(), "%s: %.10g %s",
> 					spn->getName().c_str(), spnNum->getFormatedValue(), spnNum->getUnits().c_str());
+++++++++++++  

Now, after a "make; sudo make install" from the wireshark source directory and a "cmake --build ../wiresharkSourceDir" in the wireshark build directory, I reran and was able to see that the DB loaded (I put an error message in the  entry into proto_reg_handoff_j1939() and in the check to see if the DB was parsed) - here's that code snippet:
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
void proto_reg_handoff_j1939(void) {

            std::cerr << "In Handoff" << std::endl;

        j1939_handle = create_dissector_handle( dissect_J1939, proto_j1939 );

        //Load database
        J1939DataBase ddbb;
        if(!ddbb.parseJsonFile(DATABASE_PATH)) {                //Something went wrong
            std::cerr << "Error loading Database" << std::endl;
                return;
        }
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

When I did a "sudo ./wireshark" from the run directory in the wireshark build tree, the "In Handoff" message showed up. I opened the file you sent, selected a packet, did the Decode As:
![image](https://user-images.githubusercontent.com/47369051/63530551-ad3bd080-c4d4-11e9-9987-7bc7bb56b1f4.png)
chose J1939, opened up the SAE J1939 info and got this:

![image](https://user-images.githubusercontent.com/47369051/63530674-effda880-c4d4-11e9-815e-7c12f942953d.png)

Do you see anything incorrect with what I did? Are there any other tests I should try? Thanks in advance for your help and advice on this.

**Comment by wbw60** [comment] 2019-08-22 16:59
A few more items that might be of use. Here's the "about" dialog showing what the build consists of:

![image](https://user-images.githubusercontent.com/47369051/63532826-8af88180-c4d9-11e9-8c3f-6af945666ae2.png)

Here's the plugin tab:
![image](https://user-images.githubusercontent.com/47369051/63532887-b3807b80-c4d9-11e9-9129-955b8fe940b7.png)

If I disable SAE J1939 in the Enable Protocols list:
![image](https://user-images.githubusercontent.com/47369051/63533658-37873300-c4db-11e9-98fb-18d49c5535b0.png)

I no longer have a J1939 option in the "Decode As" dialog:
![image](https://user-images.githubusercontent.com/47369051/63533721-5dacd300-c4db-11e9-94b8-95a890a90b89.png)

For comparison's sake, here's a shot of the "Decode As" from my non-customized Windows version:

![image](https://user-images.githubusercontent.com/47369051/63534058-386c9480-c4dc-11e9-861b-50bc7bf156d6.png)

And here's the enabled protocols for the standard Windows Wireshark:

![image](https://user-images.githubusercontent.com/47369051/63534166-87b2c500-c4dc-11e9-9c2f-89946e1f574f.png)

Let me know what other info could help. Thanks again for your help!

**Comment by famez** [comment] 2019-08-22 20:01
Could you tell me which version of the J1939-Framework you installed? Thanks.

**Comment by famez** [comment] 2019-08-26 21:58
Hi,

About the fix you have done 

> FWIW, I noticed 3 errors in the packet-1939.cpp files that I had fixed in a previous build (I rebuilt everything and had managed to lose my previous changes). The line numbers are off due to including iostream for debug print statements and "<" are my changes, ">" is the original:
> ++++++++++++++++++
> ![image](https://user-images.githubusercontent.com/47369051/63531054-b24d4f80-c4d5-11e9-832d-741d84e7dec2.png)
> 
> +++++++++++++
> 

It is correct. I did not tests about the wireshark dissector for a while, but I made some modifications over the J1939 library code that broke the code for the dissector. 

You can open a pull request the modifications or otherwise, I will fix that later.

Nevertheless, the problem seems to be that with this version of wireshark (3.0.3) a new layer has been added (Linux Cooked Capture). This layer was not present before and the following lines in the code (packet-1939.cpp) :
```

//Get the buffer from the upper layer so that we can obtain the ID for the Can Frame
tvbuff_t *canIdTvb = tvb_get_ds_tvb(tvb);

//Obtain the length of the concerning frame
guint32 data_length = tvb_reported_length(tvb);

//Allocate a buffer where to store the DLC (payload of the can frame)
guint8* content = (guint8*)wmem_alloc(pinfo->pool, data_length);

//Obtain the can id
guint32 canId = tvb_get_ntohl(canIdTvb, 0);

```
canId is supposed to contain the identifier for the frame, instead, it contains the first 4 octets of the Linux Cooked Capture layer (00040118 or 00010118).

These lines must be fixed. 

Sadly, I do not have the time to fix the code now, so I think it will be ready in two weeks :(

**Comment by famez** [comment] 2019-08-26 22:33
As a quick fix you can test with the following modification:

Original code:
```

 //Obtain the can id
    guint32 canId = tvb_get_ntohl(canIdTvb, 0);
```


Modified code:
```

 //Obtain the can id
    guint32 leCanId = tvb_get_ntohl(canIdTvb, 0x10);
guint32 canId = (leCanId >> 24) | ((leCanId >> 8)&0xFF00) | ((leCanId << 8)&0xFF0000) | ((leCanId << 24) &0xFF000000);

canId &= 0x1FFFFFFF;
```

For me it worked.

**Comment by wbw60** [comment] 2019-09-02 22:00
I got back from my trip and my office was closed due to the hurricane coming. Hopefully later this week after it passes I will be able to try your fix. :-(

**Comment by famez** [comment] 2019-09-03 18:54
Ok, no problem.

**Comment by famez** [comment] 2019-09-04 20:30
Please, pull the latest commit to test the dissector.

**Comment by wbw60** [comment] 2019-09-09 14:01
At long last, I was able to rebuild wireshark with your latest commit (hint to those doing this on RPI3+ machines - use "cmake -G Ninja ../wireshark_source_dir" and then "ninja -j1" in your wireshark build directory) and it worked as expected.

![image](https://user-images.githubusercontent.com/47369051/64537220-6b8a9280-d2e8-11e9-9648-3b8889c9e466.png)

Thanks much for your help in tracking this down. We can close this issue.

**Comment by famez** [comment] 2019-09-09 17:30
I am glad that it worked. Closing...

**Closed by famez** 2019-09-09 17:30 UTC
